In [1]:
import cv2
import numpy as np 
import os

In [2]:
cv2.__version__

'3.4.1'

In [53]:
def Image_Show(Image):
    cv2.imshow('Image',Image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [54]:
IMAGE_DIR = './image'
IMAGE_LIST = os.listdir(IMAGE_DIR)
images = [IMAGE_DIR +'/'+ image for image in IMAGE_LIST]
print(images)

['./image/1_lena256.jpg', './image/2_51_bus.jpg']


## Image Open
### cv2.imread(filename , flag) 
- 이미지를 열어주는 함수, Opencv-python에서는 Numpy ndarray로 저장한다.
- Flags = cv2.IMREAD_COLOR , cv2.IMREAD_GRAYSCALE , cv2.IMREAD_UNCHANGED<
- cv2.IMREAD_COLOR : 이미지 파일을 Color로 읽어들임. Default 값, Blue,Red,Green 3차원 채널로 구성
- cv2.IMREAD_GRAYSCALE : 이미지를 회색화면으로 읽어들임, Black, White로 1차원 채널로 구성
- cv2.IMREAD_UNCHANGED : 투명을 표시하는 알파채널까지 읽어 들임

In [66]:
Image = cv2.imread(images[0],cv2.IMREAD_COLOR)
print(type(Image))
print(Image.shape)
print(Image[2][:10])

<class 'numpy.ndarray'>
(225, 224, 3)
[[ 82 121 173]
 [ 79 119 172]
 [ 75 115 173]
 [ 69 110 172]
 [ 66 106 171]
 [ 62 101 170]
 [ 59  97 169]
 [ 62  95 168]
 [ 67  95 166]
 [ 77  96 163]]


In [56]:
Image = cv2.imread(images[0],cv2.IMREAD_GRAYSCALE)
print(Image.shape)
print(Image[2][:10])

(225, 224)
[132 130 128 124 121 117 114 113 113 114]


In [57]:
Image = cv2.imread(images[0],cv2.IMREAD_UNCHANGED)
print(Image.shape)
print(Image[2][:10])

(225, 224, 3)
[[ 82 121 173]
 [ 79 119 172]
 [ 75 115 173]
 [ 69 110 172]
 [ 66 106 171]
 [ 62 101 170]
 [ 59  97 169]
 [ 62  95 168]
 [ 67  95 166]
 [ 77  96 163]]


In [71]:
Image = cv2.resize(Image,(100,100))
print(Image.shape)

(100, 100, 3)


In [80]:
Image = cv2.imread(images[0])
resize_Scale = 0.5
height,width,channel = Image.shape
# 비율로도 조절이 가능
Image = cv2.resize(Image,(int(width*0.5),int(height*0.5)))
print(Image.shape)

(112, 112, 3)


## Draw Polygraph

cv2.line(), cv2.circle(), cv2.rectangle(), cv2.putText() 와 같은 함수로 도형을 그릴수 있음
### cv2.line(img,start,end,color,thickness)
- img = 이미지 파일
- Start = 선의 시작지점 (x,y)
- end = 선의 끝지점(x,y)
- Color = 선의 색상 (B,R,G)
- Thickness = 선의 굵기 

In [81]:
Image = cv2.imread(images[0])
h,w,_ = Image.shape
print(w,h)
cv2.line(Image,(int(0.3*w),int(0.3*h)),(int(0.5*w),int(0.4*h)),(255,255,255),1)
cv2.line(Image,(100,100),(200,200),(0,0,0),1)
Image_Show(Image)

224 225


### cv2.circle(img,center,radian,color,thickness)
- Img = 이미지 파일
- Center = 원의 중심점(x,y)
- Radian = 원의 반지름
- Color = 원의 색상(B,R,G)
- Thickness = 원의 굵기 , -1이면 안쪽을 채움

In [82]:
Image = cv2.imread(images[0])
h,w,_ = Image.shape
cv2.circle(Image,(int(w*0.5),int(h*0.5)),int(w*0.25),(255,255,255),1)
cv2.circle(Image,(112,112),10,(0,0,0),-1) 
Image_Show(Image)

### cv2.Polylines(img,pts,isClosed,Color,thickness)
- Img = 이미지 파일 
- Pts = 연결 좌표 
- isClosed = 닫힌 도형 여부
- Color = 색상
- Thickness = 굵기


In [83]:
points = np.array([[10,10],[12,12],[17,17],[50,50],[70,30],[100,150]],np.int32)
points = points.reshape((-1,1,2))
print(points)

[[[ 10  10]]

 [[ 12  12]]

 [[ 17  17]]

 [[ 50  50]]

 [[ 70  30]]

 [[100 150]]]


In [84]:
# IsClosed = True
Image = cv2.imread(images[0])
cv2.polylines(Image,[points],True,(0,255,255))
Image_Show(Image)

In [85]:
# IsClosed = False 
Image = cv2.imread(images[0])
cv2.polylines(Image,[points],False,(0,255,255))
Image_Show(Image)

### cv2.rectangle(img,start,end,Color,thickness)
- 정사각형(rectangle)을 그려주는 함수이다
- img = 이미지 파일
- Start = 정사각형의 시작지점 (x,y) 
- end = 정사각형의 끝지점 (x,y)

In [86]:
Image = cv2.imread(images[0])
h,w,_ = Image.shape
cv2.rectangle(Image,(int(w*0.3),int(h*0.4)),(int(w*0.7),int(h*0.6)),(255,255,255),2)
Image_Show(Image)

In [87]:
Image = cv2.imread(images[0])
h,w,_ = Image.shape
cv2.rectangle(Image,(125,125),(200,214),(255,255,255),2)
Image_Show(Image)

### cv2.putText(img,text,org,font,fontScale,Color)

- 그림에 글자를 넣어주는 함수
- img = 이미지 파일
- text = 표시할 문자열 
- org = 문자열을 표시할 위치
- font = 폰트의 타입
- fontScale = 폰트의 크기

**Font Types = FONT_HERSHEY_SIMPLEX, FONT_HERSHEY_PLAIN, FONT_HERSHEY_DUPLEX, FONT_HERSHEY_COMPLEX, 
       FONT_HERSHEY_TRIPLEX, FONT_HERSHEY_COMPLEX_SMALL, FONT_HERSHEY_SCRIPT_SIMPLEX, FONT_HERSHEY_SCRIPT_COMPLEX** 



In [88]:
Image = cv2.imread(images[0])
h,w,_ = Image.shape

Text = 'Test Text'
Font_Style = cv2.FONT_HERSHEY_SIMPLEX
cv2.rectangle(Image,(125,125),(200,214),(255,255,255),2)
cv2.putText(Image,Text,(125,135),Font_Style,0.5,(255,255,255),1)
Image_Show(Image)

## Flip, Rotate

### cv2.flip(image, flip_direction)
- Image : 이미지파일
- fiip_direction : 전환 시킬 방향, 1 : 좌우반전, 0 : 상하반전

In [89]:
Image = cv2.imread(images[0])
Image = cv2.flip(Image,1)
Image_Show(Image)

In [90]:
Image = cv2.imread(images[0])
Image = cv2.flip(Image,0)
Image_Show(Image)

### cv2.getRotationMatrix2D(center, angle, scale)
- 2차원 회전된 행렬을 생성해준다
- Center : 중심점
- Angle : 회전각
- Scale : 생성크기

### cv2.warpAffine(img, Matrix, dsize)
- 이미지를 변환행렬에 적용시켜주는 함수
- img = 변경할 이미지
- Matrix = 회전된 행렬
- dsize = 변경할 이미지의 가로,세로의 크기

In [92]:
Image = cv2.imread(images[0])
rotated_images = []
rotate_angles = [90,180,270] 
height, width ,_ = Image.shape
scale = 1.0
for angle in rotate_angles:
    Matrix = cv2.getRotationMatrix2D((width/2,height/2),angle,scale)
    rotated_images.append(cv2.warpAffine(Image,Matrix,(width,height)))

In [96]:
for rotated_image in rotated_images:
    Image_Show(rotated_image)

In [ ]:
### DeNoising Method
- Gaussian 
- Rayleigh
- Erlang, Gamma
- Exponetial
- Uniform
- Impulse